Fix security issues

diff --git a/.github/workflows/check-code-quality.yml b/.github/workflows/check-code-quality.yml
--- a/.github/workflows/check-code-quality.yml
+++ b/.github/workflows/check-code-quality.yml
@@ -23,7 +23,7 @@ on:
   pull_request:
     types: [opened, synchronize, reopened]
     # run this worflow only for code/test related changes (avoid it for documentation)
-    paths: ['**.json', '**.lock', '**.py', '**.raw', '**.toml', '**.yaml', '**.yml']
+    paths: ['**.json', '**.lock', '**.py', '**.raw', '**.sh', '**.toml', '**.yaml', '**.yml']
   workflow_dispatch:
 
 env:
@@ -39,7 +39,7 @@ jobs:
       conf: ${{ steps.filter.outputs.conf }}
     steps:
       - uses: actions/checkout@v6
-      - uses: dorny/paths-filter@v3
+      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
         id: filter
         with:
           filters: |
@@ -59,7 +59,7 @@ jobs:
           ":information_source: This job checks that you have run \`pre-commit run --all-files\` in
           your local git repository before committing."
           >> $GITHUB_STEP_SUMMARY
-      - uses: pre-commit/action@v3.0.1
+      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
 
   check-license:
     runs-on: ubuntu-latest
@@ -75,7 +75,7 @@ jobs:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.event.pull_request.head.ref }}
       - name: check License Header
-        uses: apache/skywalking-eyes/header@main
+        uses: apache/skywalking-eyes/header@8c96ee223558797cdd9eba82c0919258e1cf2dad # main
         with:
           log: debug
           mode: check
@@ -85,7 +85,6 @@ jobs:
     name: Check linting (pylint, flake8)
     needs: changes
     if: ${{ needs.changes.outputs.code == 'true' }}
-    # continue-on-error: true # run other jobs, resolve issues later
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/poetry-install
@@ -94,17 +93,19 @@ jobs:
 
       - name: Run pylint
         if: always() # even if previous steps returned a non-zero exit code
-        run: poetry run pylint "**/*.py" --output-format=colorized,parseable:./pylint-report.txt
+        run: |
+          set -x
+          poetry run pylint "**/*.py" --output-format=colorized,parseable:./pylint-report.txt
 
       - name: Run flake8
         if: always()
         run: |
-            set -x
-            poetry run flake8 . || true # run next line even if fails
-            poetry run flake8 . --output-file ./flake8-report.txt
+          set -x
+          poetry run flake8 . || true # run next line even if fails
+          poetry run flake8 . --output-file ./flake8-report.txt
 
       - name: Save reports
-        uses: actions/upload-artifact@v5
+        uses: actions/upload-artifact@v7
         if: always()
         with:
           name: check-linting
@@ -118,7 +119,6 @@ jobs:
     name: Check typing (mypy)
     needs: changes
     if: ${{ needs.changes.outputs.code == 'true' }}
-    # continue-on-error: true # run other jobs, resolve issues later
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/poetry-install
@@ -131,8 +131,6 @@ jobs:
   check-security:
     runs-on: ubuntu-latest
     name: Check security (bandit, safety, trivy)
-    # continue-on-error: true # run other jobs, resolve issues later
-    permissions: write-all
     steps:
       - uses: actions/checkout@v6
       - uses: ./.github/actions/poetry-install
@@ -157,14 +155,16 @@ jobs:
       - id: safety
         name: Run safety
         if: always()
+        env:
+            SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
         run: |
           set -x
-          poetry run safety --key ${{ secrets.SAFETY_API_KEY }} scan --detailed-output
+          poetry run safety --key $SAFETY_API_KEY scan --detailed-output
         shell: bash
 
       - name: Run Trivy vulnerability scanner
         if: always()
-        uses: aquasecurity/trivy-action@master
+        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
         env:
           TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
           TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
@@ -179,7 +179,7 @@ jobs:
 
       - name: Save reports as artifacts
         if: always()
-        uses: actions/upload-artifact@v5
+        uses: actions/upload-artifact@v7
         with:
           name: check-security
           path: |
@@ -253,12 +253,12 @@ jobs:
         shell: bash
 
       - name: Display code coverage summary in this console
-        uses: irongut/CodeCoverageSummary@v1.3.0
+        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
         with: # see https://github.com/marketplace/actions/code-coverage-summary#inputs
           filename: ./cov-report.xml
 
       - name: Save reports
-        uses: actions/upload-artifact@v5
+        uses: actions/upload-artifact@v7
         with:
           name: run-all-pytests
           path: |
@@ -272,7 +272,8 @@ jobs:
     name: Quality report (sonarqube)
     needs: [changes, check-linting, check-security, run-all-pytests] # see actions/download-artifact below
     if: ${{ needs.changes.outputs.code == 'true' }}
-    permissions: write-all # write pull request comments
+    permissions:
+      pull-requests: write # for: phwt/sonarqube-quality-gate-action
     env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_PROJECT_KEY: RS-PYTHON_rs-client-libraries
@@ -282,17 +283,17 @@ jobs:
         with:
           fetch-depth: 0 # Full history for SCM and branch analysis
       - name: Download linting reports
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v8
         with:
           name:
             check-linting
       - name: Download vulnerability reports
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v8
         with:
           name:
             check-security
       - name: Download pytest reports
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v8
         with:
           name:
             run-all-pytests
@@ -302,25 +303,29 @@ jobs:
           sed -i 's|<source>[^<]*</source>|<source>.</source>|g' ./cov-report.xml
 
       - name: Run SonarCloud Scanner
-        uses: SonarSource/sonarcloud-github-action@v2
+        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 # v7
         with:
-          # See doc:
-          # https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/languages/python/
-          # https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/importing-external-issues/importing-third-party-issues/
-          # https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/test-coverage/test-execution-parameters/
-          # https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/test-coverage/test-coverage-parameters/
+          # See doc: https://docs.sonarsource.com/sonarqube-cloud
+          #
+          # "sonar.coverage.exclusions" excludes some files from the test coverage metrics but those files are still
+          # analyzed: other metrics, duplications, coding rules...
+          #
+          # "sonar.exclusions" completely excludes some files from the analysis: those files don't appear at all
+          # in SonarQube.
+          #
           # Before, the -Dsonar.python.xunit.reportPath flag was used, but the report generated in sonarcloud.io was having a warning:
           # "No report was found for sonar.python.xunit.reportPath using pattern "./junit-xml-report.xml"
           # I changed this flag with -Dsonar.junit.reportPaths, according
+          #
           projectBaseDir: .
           args: >
             -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
             -Dsonar.organization=rs-python
+            -Dsonar.branch.name=${{ github.ref_name }}
             -Dsonar.sources=.
             -Dsonar.tests=./tests
             -Dsonar.coverage.exclusions=tests,tests/**,**/tests/**,rs_workflows/on_demand/**,rs_workflows/operation/**,rs_workflows/utils/**
             -Dsonar.exclusions=tests,tests/**,**/tests/**
-            -Dsonar.branch.name=${{ github.ref_name }}
             -Dsonar.sourceEncoding=UTF-8
             -Dsonar.language=py
             -Dsonar.python.version=${{ env.PYTHON_VERSION }}
@@ -334,7 +339,7 @@ jobs:
         run: sleep 5
 
       - name: Report quality gate result in the pull request comment
-        uses: phwt/sonarqube-quality-gate-action@v1
+        uses: phwt/sonarqube-quality-gate-action@e8842ff65b97bfa4fd4effe3ab0909f568d16e91 # v1
         id: quality-gate-result
         with:
           sonar-project-key: ${{ env.SONAR_PROJECT_KEY }}
@@ -350,13 +355,11 @@ jobs:
 
       - id: check-gate
         name: Check quality gate status
-        uses: sonarsource/sonarqube-quality-gate-action@master
+        uses: sonarsource/sonarqube-quality-gate-action@cb3ed20f9fec62b4c3b8ad9e77656c6adaade913 # master
         timeout-minutes: 5
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      # http instead of https or the url appears as *** in github, I don't know why,
-      # it may be configurable. But http works as well.
       - if: always()
         run: >
           echo "SonarCloud report:
